parameters:
  environment: phoenix
  isDynamicVersion: true
  feedType: internal # value should be "internal" or 'external' only

jobs:
  - deployment: deploy_${{ parameters.environment }}
    pool: { vmImage: 'ubuntu-18.04' }
    environment: momentum_mea_${{ parameters.environment }}
    variables:
      Environment: ${{ parameters.environment }}
      IsDynamicVersion: ${{ parameters.isDynamicVersion }}
      FeedType: ${{ parameters.feedType }}
      

    strategy:
      runOnce:
        deploy:
          steps:

          - download: current

          - task: UseDotNet@2
            inputs:
              packageType: 'sdk'              
              useGlobalJson: true
              workingDirectory: "$(Pipeline.Workspace)/project/"

          - task: DotNetCoreCLI@2
            displayName: "Build NuGet"
            condition: succeeded()
            env:
              DOTNET_CLI_TELEMETRY_OPTOUT: 1
              DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
            inputs:
              command: build
              projects: "Kmd.Momentum.Mea.Client.csproj"
              workingDirectory: "$(Pipeline.Workspace)/project/"

          - task: DotNetCoreCLI@2
            displayName: 'Pack NuGet with dynamic version'
            condition: and(succeeded(),eq(variables['isDynamicVersion'],'true'))
            inputs:
              command: pack
              packagesToPack: 'Kmd.Momentum.Mea.Client.csproj'
              buildProperties: 'VersionSuffix="$(Environment)$(Build.BuildId)"'
              packDirectory: '$(Pipeline.Workspace)/packages/$(Environment)'
              verbosityPack: 'normal'
              workingDirectory: "$(Pipeline.Workspace)/project/"

          - task: DotNetCoreCLI@2
            displayName: 'Pack NuGet without dynamic version'
            condition: and(succeeded(),eq(variables['isDynamicVersion'],'false'))
            inputs:
              command: pack
              packagesToPack: './Kmd.Momentum.Mea.Client.csproj'
              packDirectory: '$(Pipeline.Workspace)/packages/$(Environment)'
              verbosityPack: 'normal'
              nobuild: true
              workingDirectory: "$(Pipeline.Workspace)/project/"
              
          - publish: '$(Pipeline.Workspace)/packages/$(Environment)'
            displayName: 'upload NuGet Package'
            artifact: '$(Environment)'

          - task: NuGetCommand@2
            displayName: 'Push NuGet Package'
            condition: succeeded()
            inputs:
              command: 'push'
              packagesToPush: '$(Pipeline.Workspace)/packages/$(Environment)/*.nupkg'
              nuGetFeedType: $(FeedType)
              publishVstsFeed: 'Momentum/KmdMomentumMeaFeed' #Required only when "nuGetFeedType" is "internal"
              publishFeedCredentials: 'test nuget'  #Required only when "nuGetFeedType" is "external"