trigger:
- master
- dev

stages:
- stage: Build
  jobs:
  - job: build
    strategy:
      matrix:
        linux: { imageName: "ubuntu-latest" }
        mac: { imageName: "macos-latest" }
        windows: { imageName: "windows-latest" }
      maxParallel: 3
    pool:
      vmImage: $(imageName)

    steps:
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        useGlobalJson: true
        workingDirectory: "$(Pipeline.Workspace)/s/kmd-momentum-mea-client/"

    - task: DotNetCoreCLI@2
      displayName: "Build Solution"
      inputs:
        command: build
        projects: './kmd-momentum-mea-client/Kmd-Momentum-Mea-Client.sln'
        arguments: '--configuration "Release"'

    - task: DotNetCoreCLI@2
      displayName: "Build NuGet"
      inputs:
        command: build
        projects: './kmd-momentum-mea-client/src/kmd.momentum.mea.client/Kmd.Momentum.Mea.Client.csproj'
        buildProperties: 'VersionSuffix="$(Build.BuildNumber)"'

    - task: DotNetCoreCLI@2
      displayName: 'Create NuGet Package'
      inputs:
        command: pack        
        packagesToPack: './kmd-momentum-mea-client/src/kmd.momentum.mea.client/Kmd.Momentum.Mea.Client.csproj'
        buildProperties: 'VersionSuffix="$(Build.BuildNumber)"'
        packDirectory: '$(Build.ArtifactStagingDirectory)/packages/releases'
        verbosityPack: 'normal'