trigger:
- master
- dev

stages:
- stage: Build
  jobs:
  - job: build
    strategy:
      matrix:
        linux: { imageName: "ubuntu-18.04" }
        mac: { imageName: "macos-10.14" }
        windows: { imageName: "windows-2019" }
      maxParallel: 3
    pool:
      vmImage: $(imageName)

    steps:
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        useGlobalJson: true
        workingDirectory: "$(Pipeline.Workspace)/s/kmd-momentum-mea-client/"

    - task: DotNetCoreCLI@2
      displayName: "Build Solution"
      inputs:
        command: build
        projects: '$(Pipeline.Workspace)/s/kmd-momentum-mea-client/Kmd-Momentum-Mea-Client.sln'
        arguments: '--configuration "Release"'

    - task: DotNetCoreCLI@2
      displayName: 'Create NuGet Package'
      inputs:
        command: pack 
        packagesToPack: '$(Pipeline.Workspace)/s/kmd-momentum-mea-client/src/kmd.momentum.mea.client/Kmd.Momentum.Mea.Client.csproj'
        packDirectory: '$(Build.ArtifactStagingDirectory)/packages/releases'

        nologo: true