parameters:
  environment: phoenix
  isDynamicVersion: true
  feedType: internal # value should be "internal" or 'external' only

jobs:
  - deployment: deploy_${{ parameters.environment }}
    pool: { vmImage: 'ubuntu-18.04' }
    environment: momentum_mea_${{ parameters.environment }}
    variables:
      Environment: ${{ parameters.environment }}
      IsDynamicVersion: ${{ parameters.isDynamicVersion }}
      FeedType: ${{ parameters.feedType }}
      

    strategy:
      runOnce:
        deploy:
          steps:

          - download: current
            displayName: "Download artifacts"

          - task: DotNetCoreCLI@2
            displayName: 'Create NuGet Package - $(Environment) Version'
            condition: and(succeeded(),eq(variables['isDynamicVersion'],'true'))
            inputs:
              command: pack
              packagesToPack: "$(Pipeline.Workspace)/project/Kmd.Momentum.Mea.Client.csproj"
              buildProperties: 'VersionSuffix="$(Environment)$(Build.BuildId)"'
              packDirectory: '$(Pipeline.Workspace)/packages/$(Environment)'
              verbosityPack: 'normal'

          - task: DotNetCoreCLI@2
            displayName: 'Create NuGet Package - $(Environment) Version'
            condition: and(succeeded(),eq(variables['isDynamicVersion'],'false'))
            inputs:
              command: pack
              packagesToPack: "$(Pipeline.Workspace)/project/Kmd.Momentum.Mea.Client.csproj"
              packDirectory: '$(Pipeline.Workspace)/packages/$(Environment)'
              verbosityPack: 'normal'              
              
          - publish: '$(Pipeline.Workspace)/packages/$(Environment)'
            displayName: 'upload NuGet Package'
            artifact: '$(Environment)'

          - task: NuGetCommand@2
            displayName: 'Publish NuGet Package'
            condition: succeeded()
            inputs:
              command: 'push'
              packagesToPush: '$(Pipeline.Workspace)/packages/$(Environment)/*.nupkg'
              nuGetFeedType: $(FeedType)
              publishVstsFeed: 'Momentum/KmdMomentumMeaFeed' #Required only when "nuGetFeedType" is "internal"
              publishFeedCredentials: 'test nuget'  #Required only when "nuGetFeedType" is "external"