parameters:
  environment: phoenix
  isDynamicVersion: true
  feedType: internal # value should be "internal" or 'external' only

jobs:
  - deployment: deploy_${{ parameters.environment }}
    pool: { vmImage: 'ubuntu-18.04' }
    environment: momentum_mea_${{ parameters.environment }}
    variables:
      Environment: ${{ parameters.environment }}
      IsDynamicVersion: ${{ parameters.isDynamicVersion }}
      FeedType: ${{ parameters.feedType }}
      

    strategy:
      runOnce:
        deploy:
          steps:

          - download: current

          - task: DotNetCoreCLI@2
            displayName: 'Pack NuGet with dynamic version'
            condition: and(succeeded(),eq(variables['isDynamicVersion'],'true'))
            inputs:
              command: pack
              packagesToPack: '**/*.csproj'
              buildProperties: 'VersionSuffix="$(Environment)$(Build.BuildId)"'
              packDirectory: '$(Build.ArtifactStagingDirectory)/packages/$(Environment)'
              verbosityPack: 'normal'

          - task: DotNetCoreCLI@2
            displayName: 'Pack NuGet without dynamic version'
            condition: and(succeeded(),eq(variables['isDynamicVersion'],'false'))
            inputs:
              command: pack
              packagesToPack: '**/*.csproj'
              packDirectory: '$(Build.ArtifactStagingDirectory)/packages/$(Environment)'
              verbosityPack: 'normal'
              
          - publish: '$(Build.ArtifactStagingDirectory)/packages/$(Environment)'
            displayName: 'upload NuGet Package'
            artifact: '$(Environment)'

          - task: NuGetCommand@2
            displayName: 'Push NuGet Package'
            condition: succeeded()
            inputs:
              command: 'push'
              packagesToPush: '$(Build.ArtifactStagingDirectory)/packages/$(Environment)/*.nupkg'
              nuGetFeedType: $(FeedType)
              publishVstsFeed: 'Momentum/KmdMomentumMeaFeed' #Required only when "nuGetFeedType" is "internal"
              publishFeedCredentials: 'test nuget'  #Required only when "nuGetFeedType" is "external"