// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Kmd.Momentum.Mea.Client.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class TaskDataResponseModel
    {
        /// <summary>
        /// Initializes a new instance of the TaskDataResponseModel class.
        /// </summary>
        public TaskDataResponseModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the TaskDataResponseModel class.
        /// </summary>
        /// <param name="taskState">Possible values include: 'Active',
        /// 'Completed', 'Canceled', 'Started', 'DeadlineExceeded'</param>
        public TaskDataResponseModel(System.Guid? taskId = default(System.Guid?), string title = default(string), string description = default(string), System.DateTime? deadline = default(System.DateTime?), System.DateTime? createAt = default(System.DateTime?), System.DateTime? stateChangedAt = default(System.DateTime?), string taskState = default(string), IList<AssignedActors> assignedActors = default(IList<AssignedActors>), Reference reference = default(Reference))
        {
            TaskId = taskId;
            Title = title;
            Description = description;
            Deadline = deadline;
            CreateAt = createAt;
            StateChangedAt = stateChangedAt;
            TaskState = taskState;
            AssignedActors = assignedActors;
            Reference = reference;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "taskId")]
        public System.Guid? TaskId { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "title")]
        public string Title { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "description")]
        public string Description { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "deadline")]
        public System.DateTime? Deadline { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "createAt")]
        public System.DateTime? CreateAt { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "stateChangedAt")]
        public System.DateTime? StateChangedAt { get; private set; }

        /// <summary>
        /// Gets or sets possible values include: 'Active', 'Completed',
        /// 'Canceled', 'Started', 'DeadlineExceeded'
        /// </summary>
        [JsonProperty(PropertyName = "taskState")]
        public string TaskState { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "assignedActors")]
        public IList<AssignedActors> AssignedActors { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "reference")]
        public Reference Reference { get; set; }

    }
}
